{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8c6329cf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ">>> Computing ACF features per store...\n",
      ">>> ACF table shape: (54, 8)\n",
      ">>> ACF table columns: ['store_nbr', 'first_acf_original', 'sumsq_acf_original', 'first_acf_diff1', 'sumsq_acf_diff1', 'first_acf_diff2', 'sumsq_acf_diff2', 'seasonal_acf']\n",
      ">>> ACF table head:\n",
      "   store_nbr  first_acf_original  sumsq_acf_original  first_acf_diff1  \\\n",
      "0          1           -0.060393            0.028752        -0.521795   \n",
      "1          2           -0.067574            0.056076        -0.527110   \n",
      "2          3           -0.089117            0.125725        -0.534634   \n",
      "3          4           -0.088535            0.158816        -0.531400   \n",
      "4          5           -0.095750            0.112813        -0.524814   \n",
      "\n",
      "   sumsq_acf_diff1  first_acf_diff2  sumsq_acf_diff2  seasonal_acf  \n",
      "0         0.303261        -0.674733         0.529303     -0.072911  \n",
      "1         0.326922        -0.679632         0.545572      0.043151  \n",
      "2         0.398940        -0.699452         0.658790     -0.065157  \n",
      "3         0.544911        -0.678774         0.850916     -0.103784  \n",
      "4         0.425607        -0.686893         0.706142     -0.037032  \n",
      ">>> Expected ACF columns present: True\n",
      ">>> Adding features to train and test...\n",
      ">>> Merging ACF features...\n",
      ">>> Before merge - df shape: (3000888, 22)\n",
      ">>> ACF lookup shape: (54, 8)\n",
      ">>> After merge - df shape: (3000888, 29)\n",
      "[INFO] first_acf_original successfully merged, non-null count: 3000888\n",
      "[INFO] sumsq_acf_original successfully merged, non-null count: 3000888\n",
      "[INFO] first_acf_diff1 successfully merged, non-null count: 3000888\n",
      "[INFO] sumsq_acf_diff1 successfully merged, non-null count: 3000888\n",
      "[INFO] first_acf_diff2 successfully merged, non-null count: 3000888\n",
      "[INFO] sumsq_acf_diff2 successfully merged, non-null count: 3000888\n",
      "[INFO] seasonal_acf successfully merged, non-null count: 3000888\n",
      ">>> Merging ACF features...\n",
      ">>> Before merge - df shape: (28512, 21)\n",
      ">>> ACF lookup shape: (54, 8)\n",
      ">>> After merge - df shape: (28512, 28)\n",
      "[INFO] first_acf_original successfully merged, non-null count: 28512\n",
      "[INFO] sumsq_acf_original successfully merged, non-null count: 28512\n",
      "[INFO] first_acf_diff1 successfully merged, non-null count: 28512\n",
      "[INFO] sumsq_acf_diff1 successfully merged, non-null count: 28512\n",
      "[INFO] first_acf_diff2 successfully merged, non-null count: 28512\n",
      "[INFO] sumsq_acf_diff2 successfully merged, non-null count: 28512\n",
      "[INFO] seasonal_acf successfully merged, non-null count: 28512\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.\n",
      "  self._init_dates(dates, freq)\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
      "  warnings.warn(\"Maximum Likelihood optimization failed to \"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ">>> Submission saved to 'my_submission.csv'\n",
      "\n",
      ">>> DEBUGGING INFO:\n",
      ">>> Sample of ACF values for first few stores:\n",
      "   store_nbr  first_acf_original  sumsq_acf_original  first_acf_diff1  \\\n",
      "0          1           -0.060393            0.028752        -0.521795   \n",
      "1          2           -0.067574            0.056076        -0.527110   \n",
      "2          3           -0.089117            0.125725        -0.534634   \n",
      "3          4           -0.088535            0.158816        -0.531400   \n",
      "4          5           -0.095750            0.112813        -0.524814   \n",
      "5          6           -0.106356            0.199000        -0.530427   \n",
      "6          7           -0.094841            0.081826        -0.519329   \n",
      "7          8           -0.079998            0.077848        -0.538062   \n",
      "8          9           -0.102175            0.043008        -0.512161   \n",
      "9         10           -0.065051            0.101439        -0.497920   \n",
      "\n",
      "   sumsq_acf_diff1  first_acf_diff2  sumsq_acf_diff2  seasonal_acf  \n",
      "0         0.303261        -0.674733         0.529303     -0.072911  \n",
      "1         0.326922        -0.679632         0.545572      0.043151  \n",
      "2         0.398940        -0.699452         0.658790     -0.065157  \n",
      "3         0.544911        -0.678774         0.850916     -0.103784  \n",
      "4         0.425607        -0.686893         0.706142     -0.037032  \n",
      "5         0.607394        -0.689848         0.947832     -0.081944  \n",
      "6         0.364863        -0.659558         0.550073     -0.010149  \n",
      "7         0.403364        -0.702011         0.697493     -0.052797  \n",
      "8         0.300189        -0.666556         0.511025      0.026805  \n",
      "9         0.403865        -0.645428         0.615710     -0.092527  \n",
      "\n",
      ">>> Summary statistics for ACF features:\n",
      "first_acf_original: mean=-0.0659, std=0.0313, min=-0.1082, max=0.0343\n",
      "sumsq_acf_original: mean=0.1094, std=0.0551, min=0.0132, max=0.2238\n",
      "seasonal_acf: mean=-0.0218, std=0.0570, min=-0.1235, max=0.1493\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n",
      "  return get_prediction_index(\n",
      "/Users/donaldaadithiyan/Desktop/Uni/Sem 5/Time Series-Assignment/venv/lib/python3.9/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n",
      "  return get_prediction_index(\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from statsmodels.tsa.statespace.sarimax import SARIMAX\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "\n",
    "# ============================\n",
    "# 0️⃣ Load & prepare data\n",
    "# ============================\n",
    "merged_train_df = pd.read_csv('merged_train_df.csv')\n",
    "test_df = pd.read_csv(\"test_df.csv\")\n",
    "\n",
    "merged_train_df['date'] = pd.to_datetime(merged_train_df['date'])\n",
    "test_df['date'] = pd.to_datetime(test_df['date'])\n",
    "\n",
    "merged_train_df = merged_train_df.sort_values(\"date\").reset_index(drop=True)\n",
    "test_df = test_df.sort_values(\"date\").reset_index(drop=True)\n",
    "\n",
    "merged_train_df['store_nbr'] = merged_train_df['store_nbr'].astype(int)\n",
    "test_df['store_nbr'] = test_df['store_nbr'].astype(int)\n",
    "\n",
    "# ============================\n",
    "# 1️⃣ ACF helper\n",
    "# ============================\n",
    "def acf_features(series, seasonal_lag=7):\n",
    "    s = series.dropna()\n",
    "    if len(s) < 15:\n",
    "        return pd.Series({k: 0.0 for k in [\n",
    "            \"first_acf_original\",\"sumsq_acf_original\",\n",
    "            \"first_acf_diff1\",\"sumsq_acf_diff1\",\n",
    "            \"first_acf_diff2\",\"sumsq_acf_diff2\",\n",
    "            \"seasonal_acf\"\n",
    "        ]})\n",
    "    try:\n",
    "        acfs = [s.autocorr(lag=i) if not pd.isna(s.autocorr(lag=i)) else 0.0 for i in range(1,11)]\n",
    "        first_acf = acfs[0]\n",
    "        diff1 = s.diff().dropna()\n",
    "        acfs_diff1 = [diff1.autocorr(lag=i) if len(diff1) > i else 0.0 for i in range(1,11)]\n",
    "        first_acf_diff1 = acfs_diff1[0] if len(acfs_diff1)>0 else 0.0\n",
    "        diff2 = diff1.diff().dropna()\n",
    "        acfs_diff2 = [diff2.autocorr(lag=i) if len(diff2) > i else 0.0 for i in range(1,11)]\n",
    "        first_acf_diff2 = acfs_diff2[0] if len(acfs_diff2)>0 else 0.0\n",
    "        seasonal_acf = s.autocorr(lag=seasonal_lag) if len(s) > seasonal_lag else 0.0\n",
    "\n",
    "        out = {\n",
    "            \"first_acf_original\": first_acf,\n",
    "            \"sumsq_acf_original\": np.sum(np.square(acfs)),\n",
    "            \"first_acf_diff1\": first_acf_diff1,\n",
    "            \"sumsq_acf_diff1\": np.sum(np.square(acfs_diff1)),\n",
    "            \"first_acf_diff2\": first_acf_diff2,\n",
    "            \"sumsq_acf_diff2\": np.sum(np.square(acfs_diff2)),\n",
    "            \"seasonal_acf\": seasonal_acf\n",
    "        }\n",
    "    except:\n",
    "        out = {k:0.0 for k in [\n",
    "            \"first_acf_original\",\"sumsq_acf_original\",\n",
    "            \"first_acf_diff1\",\"sumsq_acf_diff1\",\n",
    "            \"first_acf_diff2\",\"sumsq_acf_diff2\",\n",
    "            \"seasonal_acf\"\n",
    "        ]}\n",
    "    return pd.Series(out)\n",
    "\n",
    "# ============================\n",
    "# 2️⃣ Compute ACF table correctly - FIXED\n",
    "# ============================\n",
    "print(\">>> Computing ACF features per store...\")\n",
    "\n",
    "# Compute ACF features per store\n",
    "acf_table_raw = merged_train_df.groupby(\"store_nbr\")[\"sales\"].apply(acf_features)\n",
    "\n",
    "# FIXED: Properly convert to DataFrame by unstacking\n",
    "acf_table = acf_table_raw.unstack().reset_index()\n",
    "\n",
    "print(\">>> ACF table shape:\", acf_table.shape)\n",
    "print(\">>> ACF table columns:\", acf_table.columns.tolist())\n",
    "print(\">>> ACF table head:\")\n",
    "print(acf_table.head())\n",
    "\n",
    "# Verify we have the expected columns\n",
    "expected_acf_cols = ['first_acf_original','sumsq_acf_original','first_acf_diff1','sumsq_acf_diff1',\n",
    "                     'first_acf_diff2','sumsq_acf_diff2','seasonal_acf']\n",
    "print(\">>> Expected ACF columns present:\", all(col in acf_table.columns for col in expected_acf_cols))\n",
    "\n",
    "# ============================\n",
    "# 3️⃣ Feature engineering with proper merge\n",
    "# ============================\n",
    "def feature_engineering(df, acf_lookup):\n",
    "    df = df.copy()\n",
    "    df['store_family'] = df['store_nbr'].astype(str) + \"_\" + df['family'].astype(str)\n",
    "    df['promo_holiday'] = df['onpromotion'] * df['isHoliday']\n",
    "    df['oil_price_diff'] = df.groupby('store_nbr')['oil_price'].diff().fillna(0)\n",
    "    df['oil_price_rolling_7'] = df.groupby('store_nbr')['oil_price'].rolling(7, min_periods=1).mean().reset_index(0, drop=True).bfill()\n",
    "    df['oil_price_7d_avg'] = df['oil_price_rolling_7']\n",
    "    df['onpromotion_7d_sum'] = df.groupby('store_nbr')['onpromotion'].rolling(7, min_periods=1).sum().reset_index(0, drop=True).fillna(0)\n",
    "    df['salary_promo'] = df['salary_day_impact'] * df['onpromotion']\n",
    "\n",
    "    print(\">>> Merging ACF features...\")\n",
    "    print(\">>> Before merge - df shape:\", df.shape)\n",
    "    print(\">>> ACF lookup shape:\", acf_lookup.shape)\n",
    "    \n",
    "    df = df.merge(acf_lookup, on=\"store_nbr\", how=\"left\")\n",
    "    print(\">>> After merge - df shape:\", df.shape)\n",
    "\n",
    "    acf_cols = ['first_acf_original','sumsq_acf_original','first_acf_diff1','sumsq_acf_diff1',\n",
    "                'first_acf_diff2','sumsq_acf_diff2','seasonal_acf']\n",
    "    \n",
    "    for col in acf_cols:\n",
    "        if col not in df.columns:\n",
    "            print(f\"[WARN] {col} missing in merged df, filling with 0\")\n",
    "            df[col] = 0.0\n",
    "        else:\n",
    "            print(f\"[INFO] {col} successfully merged, non-null count: {df[col].notna().sum()}\")\n",
    "            df[col] = df[col].fillna(0.0)\n",
    "\n",
    "    return df\n",
    "\n",
    "print(\">>> Adding features to train and test...\")\n",
    "train_fe = feature_engineering(merged_train_df, acf_table)\n",
    "test_fe = feature_engineering(test_df, acf_table)\n",
    "\n",
    "# ============================\n",
    "# 4️⃣ Encode categoricals\n",
    "# ============================\n",
    "exog_cols = ['onpromotion','oil_price','isHoliday','earthquake_impact','salary_day_impact',\n",
    "             'promo_holiday','oil_price_diff','oil_price_rolling_7','oil_price_7d_avg',\n",
    "             'onpromotion_7d_sum','salary_promo',\n",
    "             'first_acf_original','sumsq_acf_original','first_acf_diff1','sumsq_acf_diff1',\n",
    "             'first_acf_diff2','sumsq_acf_diff2','seasonal_acf']\n",
    "\n",
    "cat_cols = [\"city\",\"state\",\"family\",\"type\",\"store_family\"]\n",
    "\n",
    "cat_encoders = {}\n",
    "for col in cat_cols:\n",
    "    le = LabelEncoder()\n",
    "    combined_values = pd.concat([train_fe[col].astype(str), test_fe[col].astype(str)]).unique()\n",
    "    le.fit(combined_values)\n",
    "    train_fe[col] = le.transform(train_fe[col].astype(str))\n",
    "    test_fe[col] = le.transform(test_fe[col].astype(str))\n",
    "    cat_encoders[col] = le\n",
    "    exog_cols.append(col)\n",
    "\n",
    "# ============================\n",
    "# 5️⃣ Train SARIMAX per store\n",
    "# ============================\n",
    "predictions = []\n",
    "\n",
    "common_stores = set(train_fe['store_nbr'].unique()) & set(test_fe['store_nbr'].unique())\n",
    "\n",
    "for store_num in sorted(common_stores):\n",
    "    train_store_df = train_fe[train_fe['store_nbr']==store_num].sort_values('date')\n",
    "    test_store_df = test_fe[test_fe['store_nbr']==store_num].sort_values('date')\n",
    "\n",
    "    # Use the correct sales column\n",
    "    y_train = train_store_df['sales']\n",
    "\n",
    "    if len(y_train) < 10:\n",
    "        y_pred = pd.Series([y_train.mean()] * len(test_store_df))\n",
    "        out = test_store_df[[\"id\"]].copy()\n",
    "        out[\"sales\"] = y_pred\n",
    "        predictions.append(out)\n",
    "        continue\n",
    "\n",
    "    available_exog = [c for c in exog_cols if c in train_store_df.columns and c in test_store_df.columns]\n",
    "    if len(available_exog) == 0:\n",
    "        y_pred = pd.Series([y_train.mean()] * len(test_store_df))\n",
    "        out = test_store_df[[\"id\"]].copy()\n",
    "        out[\"sales\"] = y_pred\n",
    "        predictions.append(out)\n",
    "        continue\n",
    "\n",
    "    exog_train = train_store_df[available_exog].fillna(0)\n",
    "    exog_test = test_store_df[available_exog].fillna(0)\n",
    "\n",
    "    try:\n",
    "        model = SARIMAX(y_train, order=(1,1,1), seasonal_order=(0,0,0,0),\n",
    "                        exog=exog_train, enforce_stationarity=False, enforce_invertibility=False)\n",
    "        model_fit = model.fit(disp=False, maxiter=50)\n",
    "        y_pred = model_fit.forecast(steps=len(exog_test), exog=exog_test)\n",
    "    except:\n",
    "        y_pred = pd.Series([y_train.mean()] * len(exog_test))\n",
    "\n",
    "    y_pred = np.maximum(y_pred, 0)\n",
    "    out = test_store_df[[\"id\"]].copy()\n",
    "    out[\"sales\"] = y_pred.values\n",
    "    predictions.append(out)\n",
    "\n",
    "final_preds = pd.concat(predictions, ignore_index=True)\n",
    "\n",
    "# ============================\n",
    "# 6️⃣ Submission\n",
    "# ============================\n",
    "submission_df = final_preds.copy()\n",
    "submission_df['sales'] = submission_df['sales'].astype(float)\n",
    "submission_df['sales'] = submission_df['sales'].fillna(0)\n",
    "submission_df.to_csv(\"my_submission.csv\", index=False)\n",
    "print(\">>> Submission saved to 'my_submission.csv'\")\n",
    "\n",
    "# ============================\n",
    "# 7️⃣ Debugging output\n",
    "# ============================\n",
    "print(\"\\n>>> DEBUGGING INFO:\")\n",
    "print(\">>> Sample of ACF values for first few stores:\")\n",
    "print(acf_table.head(10))\n",
    "print(\"\\n>>> Summary statistics for ACF features:\")\n",
    "for col in ['first_acf_original','sumsq_acf_original','seasonal_acf']:\n",
    "    if col in acf_table.columns:\n",
    "        print(f\"{col}: mean={acf_table[col].mean():.4f}, std={acf_table[col].std():.4f}, min={acf_table[col].min():.4f}, max={acf_table[col].max():.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "d245dcc2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "id                            int64\n",
       "date                 datetime64[ns]\n",
       "store_nbr                     int64\n",
       "family                       object\n",
       "sales                       float64\n",
       "onpromotion                   int64\n",
       "oil_price                   float64\n",
       "city                         object\n",
       "state                        object\n",
       "type                         object\n",
       "cluster                       int64\n",
       "isHoliday                     int64\n",
       "earthquake_impact             int64\n",
       "salary_day_impact             int64\n",
       "transactions                float64\n",
       "dtype: object"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "merged_train_df.dtypes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "fc0a04be",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "id                            int64\n",
       "date                 datetime64[ns]\n",
       "store_nbr                     int64\n",
       "family                       object\n",
       "onpromotion                   int64\n",
       "earthquake_impact             int64\n",
       "salary_day_impact             int64\n",
       "isHoliday                     int64\n",
       "oil_price                   float64\n",
       "city                         object\n",
       "state                        object\n",
       "type                         object\n",
       "cluster                       int64\n",
       "transactions                float64\n",
       "dtype: object"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "test_df.dtypes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "3f133a6e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "NaN values per column:\n",
      " id       0\n",
      "sales    0\n",
      "dtype: int64\n",
      "Infinite values per column:\n",
      " id       0\n",
      "sales    0\n",
      "dtype: int64\n"
     ]
    }
   ],
   "source": [
    "submission = pd.read_csv(\"my_submission_clean.csv\")\n",
    "\n",
    "# Check for NaN\n",
    "print(\"NaN values per column:\\n\", submission.isna().sum())\n",
    "\n",
    "# Check for inf\n",
    "print(\"Infinite values per column:\\n\", np.isinf(submission).sum())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "cb04ff99",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Empty DataFrame\n",
      "Columns: [id, sales]\n",
      "Index: []\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "submission = pd.read_csv(\"my_submission_clean.csv\")\n",
    "\n",
    "# Find rows where sales is infinite\n",
    "mask = np.isinf(submission[\"sales\"])\n",
    "\n",
    "# Show the offending rows\n",
    "print(submission.loc[mask])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "3b51f885",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/fv/7g0st0sd2gj1ztjzwt7t0s2c0000gn/T/ipykernel_60960/1686795528.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
      "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
      "\n",
      "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
      "\n",
      "\n",
      "  submission[\"sales\"].replace([np.inf, -np.inf], np.nan, inplace=True)\n",
      "/var/folders/fv/7g0st0sd2gj1ztjzwt7t0s2c0000gn/T/ipykernel_60960/1686795528.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
      "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
      "\n",
      "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
      "\n",
      "\n",
      "  submission[\"sales\"].fillna(method=\"ffill\", inplace=True)\n",
      "/var/folders/fv/7g0st0sd2gj1ztjzwt7t0s2c0000gn/T/ipykernel_60960/1686795528.py:10: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.\n",
      "  submission[\"sales\"].fillna(method=\"ffill\", inplace=True)\n",
      "/var/folders/fv/7g0st0sd2gj1ztjzwt7t0s2c0000gn/T/ipykernel_60960/1686795528.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
      "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
      "\n",
      "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
      "\n",
      "\n",
      "  submission[\"sales\"].fillna(method=\"bfill\", inplace=True)\n",
      "/var/folders/fv/7g0st0sd2gj1ztjzwt7t0s2c0000gn/T/ipykernel_60960/1686795528.py:13: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.\n",
      "  submission[\"sales\"].fillna(method=\"bfill\", inplace=True)\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "submission = pd.read_csv(\"my_submission.csv\")\n",
    "\n",
    "# Replace inf with NaN first (so ffill works)\n",
    "submission[\"sales\"].replace([np.inf, -np.inf], np.nan, inplace=True)\n",
    "\n",
    "# Forward fill\n",
    "submission[\"sales\"].fillna(method=\"ffill\", inplace=True)\n",
    "\n",
    "# (Optional) if the very first row is NaN/inf, ffill won’t work — so backfill as fallback\n",
    "submission[\"sales\"].fillna(method=\"bfill\", inplace=True)\n",
    "\n",
    "# Save cleaned file\n",
    "submission.to_csv(\"my_submission_clean.csv\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b42f2b12",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "▶️ Test set ID range: 3000888 to 3029399\n",
      "▶️ Submission ID range: 3000888 to 3029399\n",
      "✅ All submission IDs are inside test_df.\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "# Load your files\n",
    "test_df = pd.read_csv(\"test_df.csv\")\n",
    "submission = pd.read_csv(\"my_submission.csv\")\n",
    "\n",
    "# Check the range of IDs\n",
    "print(\"▶️ Test set ID range:\", test_df[\"id\"].min(), \"to\", test_df[\"id\"].max())\n",
    "print(\"▶️ Submission ID range:\", submission[\"id\"].min(), \"to\", submission[\"id\"].max())\n",
    "\n",
    "# Also check for IDs in submission but not in test\n",
    "extra_ids = set(submission[\"id\"]) - set(test_df[\"id\"])\n",
    "if extra_ids:\n",
    "    print(\"⚠️ IDs present in submission but not in test:\", list(extra_ids)[:10], \"...\")\n",
    "else:\n",
    "    print(\"✅ All submission IDs are inside test_df.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
